/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctpv;

import static ctpv.HiloInterna.RUTA_FICHERO;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import tpv.ProductoPedido;

/**
 *
 * @author Yeray
 */
public class CTPV extends javax.swing.JFrame {

    /**
     * Creates new form CTPV
     */
    public CTPV() throws IOException {
        initComponents();

        //Establecer el icono
        ImageIcon icono = new ImageIcon("..\\TPV\\src\\imagenes\\tpv.png");
        this.setIconImage(icono.getImage());

        Thread escuchador = new Thread(new HiloEscuchador(this));
        escuchador.start();
    }

    public static synchronized void escribirFichero(HashMap<String, ProductoPedido> mapa, int numeroTpv) {
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            //Abro el fichero
            fichero = new FileWriter(RUTA_FICHERO, true); //Ponemos true para sobreescribir
            pw = new PrintWriter(fichero);

            //
            double totalCuenta = 0;

            //Introduzco datos en el fichero
            //Añadir la fecha del sistema
            //Formateando la fecha:
            Date fechaActual = new Date();
            DateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

            //Fecha actual desglosada:
            Calendar fecha = Calendar.getInstance();
            int año = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH) + 1;
            int dia = fecha.get(Calendar.DAY_OF_MONTH);

            pw.write(dia + "-" + mes + "-" + año + "\r\n");

            //Recorro el mapa
            for (String key : mapa.keySet()) {
                //Lo mostramos en la lista
                ProductoPedido pedido = mapa.get(key);
                pw.write("\t" + pedido.toString() + "\t");
                pw.write("\r\n");

                //Redondear los decimales
                //totalCuenta += Math.round(pedido.getTotal()*Math.pow(10,2))/Math.pow(10,2);
            }

            //TOTAL de ese pedido
            //pw.write("\tTOTAL: " + totalCuenta + "\r\n");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (null != fichero) {
                    fichero.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POP-CTPV");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(6);
        setMaximumSize(getMaximumSize());
        setMinimumSize(getMaximumSize());
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CTPV().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CTPV.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
